server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/_Microservices_
    username: postgres
    password: Root@0234
  application:
     name: HOTEL-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


